### ISSUE TITLE
Audio Mod crashing on 1.18.2

### ISSUE THREAD

**Issue by WallSama** [Keksuccino/FancyMenu-Audio-Extension#1]
Hello Keksuccino, I am currently trying to use your fancymenu audio extension mod with my current modpack. Normal Fancymenu works just fine and I have even used the 1.16.5 version with audio perfectly. However when creating a 1.18.2 pack, every time I have the jar file in the mod folder, the game seems to crash. I have attached a crashlog here: https://paste.ee/p/PxrWH . Any help would be greatly appreciated, thank you!

**Comment by Keksuccino** [comment]
Hi :)

There are several problems with your instance.

I don't see Auudio in the mod list. This mod is a dependency of the audio extension.

You're using MultiMC, which I don't officially support. Maybe the extension isn't compatible with it.

The last error I see in the log is from Lithium. I'm on mobile rn and can't really read the log in a way that doesn't drive me nuts, but looks like this could cause the crash.

Please check if one of the things above solves your issue.

**Comment by WallSama** [comment]
Ok so it seemed possible solution 1 fixed it. I was using MultiMC to get a crash report easier, but I forgot that it would not download dependencies. After moving the modpack to curseforge and installing the mod through there everything seems to be working fine now. Thank you for your help
