### ISSUE TITLE
Is this mod client-side exclusive?

### ISSUE THREAD

**Issue by F0xtastic** [Keksuccino/FancyMenu-Audio-Extension#4]
Hello, I'm keep a list of mods that are client-side exclusive so I can easily spot and remove them from servers to prevent possible issues (plus to offer recommendations for those who want client-side exclusive mods). Based on the description your mod sounds unlikely to be required on a server, but as it's not explicitly stated I wanted to ask for confirmation.

Is this mod client-side exclusive, server-side optional, or?

Thanks for your time!

**Comment by Keksuccino** [comment]
It does nothing on a server, but it shouldn't crash it :) But yeah, it's a client mod.
